runtime: nodejs18
env_variables:
  DB_SOCKET: "/cloudsql/smiling-cistern-350606:asia-southeast2:elenardi"
  DB_HOST: "localhost"
  DB_PORT: 3306
  DB_DATABASE: "shamo_rest_api"
  DB_USERNAME: "elenardi"
  DB_PASSWORD: "Elen275@"
  JWT_SECRET: dfdhhf8gh523reh6qedn37dferpoawdn381j
  JWT_EXPIRATION: 720h